create table COMPETITION
(
    ID bigint generated by default as identity primary key,
    COMPETITION_TYPE varchar(10),
    NAME varchar(30),
    GAME_TYPE varchar(30)
);

create table TEAM
(
    ID bigint generated by default as identity primary key,
    NAME varchar(30)
);

create table COMPETITION_TEAMS 
(
    COMPETITION bigint, 
    TEAM bigint
);

create table FIXTURE
(
    ID bigint generated by default as identity primary key,
    COMPETITION bigint,
    HOME_TEAM bigint,
    AWAY_TEAM bigint,
    MATCH_DATE date
);

create table PLAYER
(
    ID bigint generated by default as identity primary key,
    TEAM bigint,
    FIRST_NAME varchar(30),
    LAST_NAME varchar(30),
    PHONE_NUMBER varchar(20)
);

create table RESULT
(
    ID bigint generated by default as identity primary key,
    FIXTURE bigint,
    HOME_PRIMARY_SCORE bigint,
    HOME_SECONDARY_SCORE bigint,
    AWAY_PRIMARY_SCORE bigint,
    AWAY_SECONDARY_SCORE bigint
);

create table GAME_EVENT
(
   ID bigint generated by default as identity primary key,
   SCORE_TYPE bigint,
   PLAYER bigint,
   PLAYER_UNKNOWN varchar(30),
   SCORE_TIME int
);

create table USER
(
    ID bigint generated by default as identity primary key,
    EMAIL varchar(30),
    FIRST_NAME varchar(30),
    LAST_NAME varchar(30),
    AGE bigint
);